apiVersion: v1
kind: Service
metadata:
  name: myapp-{{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: myapp
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 8080
